#!/bin/bash

# Assicurati che le istanze precedenti siano terminate
pkill -f Dooble

# Attendi un momento per assicurarsi che eventuali istanze precedenti siano terminate
sleep 1

chmod +x /opt/dooble/Dooble

# Avvia Dooble con l'URL specificato
/opt/dooble/Dooble --load-url https://whatsmyip.com --full-screen --private &

# Aspetta che la finestra appaia prima di renderla a schermo intero
sleep 3

# Applica la modalità a schermo intero
wmctrl -r "Dooble" -b add,fullscreen