services:
  rdp-browser:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOME_PAGE: https://whatsmyip.com
    ports:
      - "3389:3389"
    environment:
      - DEFAULT_USER=testuser
      - DEFAULT_PASSWORD=password
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
